USE EMPRESAHB26;

--SELECT * FROM EMPREGADO

IF OBJECT_ID('dbo.EMPREGADO_HABILIDAD', 'U') IS NOT NULL
    DROP TABLE dbo.EMPREGADO_HABILIDAD;
GO

IF OBJECT_ID('dbo.HABILIDADES', 'U') IS NOT NULL
    DROP TABLE dbo.HABILIDADES;
GO

CREATE TABLE HABILIDADES (
	NumHabilidad INT IDENTITY(1,1),
	Habilidad VARCHAR(60) NOT NULL,
	CONSTRAINT PK_HABILIDAD PRIMARY KEY (NumHabilidad),
	CONSTRAINT UQ_Habilidad UNIQUE (Habilidad)
)

GO
CREATE TABLE EMPREGADO_HABILIDAD (
	NSS_Empregado VARCHAR(15),
	NumHabilidad int,
	CONSTRAINT PK_EMPREGADO_HABILIDAD PRIMARY KEY (NSS_Empregado, NumHabilidad),
	CONSTRAINT FK_NSS_EMPREGADO_HABILIDAD FOREIGN KEY (NSS_Empregado) REFERENCES EMPREGADO (NSS),
	CONSTRAINT FK_HABILIDAD_EMPREGADO_HABILIDAD FOREIGN KEY (NumHabilidad) REFERENCES HABILIDADES (NumHabilidad)
)
