DROP TABLE IF EXISTS dbo.FAMILIARES;
/*
IF EXISTS  (
	SELECT * 
	FROM SYS.TABLES 
	WHERE NAME = 'FAMILIARES' AND SCHEMA_ID = SCHEMA_ID('dbo'))
	
	BEGIN 
		DROP TABLE dbo.FAMILIARES
		PRINT ('BORRADA LA ABLA FAMILIARES')

	END

GO
CREATE TABLE FAMILIARES (
	Numero SMALLINT NOT NULL, 
	NSS VARCHAR(15) NOT NULL,
	NOMBRE  VARCHAR(25) NOT NULL,
	APELIDO1 VARCHAR(25) NOT NULL,
	APELIDO2 VARCHAR(25) NULL,
	NSS_EMPREGADO VARCHAR(15) NOT NULL,

	CONSTRAINT PK_FAMILIARES PRIMARY KEY (NSS),
	CONSTRAINT FK_FAMILIAR_EMPREGADO FOREIGN KEY (NSS_EMPREGADO) REFERENCES EMPREGADO (NSS)
)

GO
ALTER TABLE FAMILIARES
	ADD CONSTRAINT UQ_FAMILIAR_NSS UNIQUE (NSS, NSS_EMPREGADO)
*/



	--// Ejercicio 2 

	-- VEHICULOPROPROO, RENTING 

IF EXISTS  (
	SELECT * 
	FROM SYS.TABLES 
	WHERE NAME = 'VEHICULO_PROPIO' AND SCHEMA_ID = SCHEMA_ID('dbo'))
	
	BEGIN 
		DROP TABLE dbo.VEHICULO_PROPIO

		PRINT ('BORRADA LA TABLA VEHICULOS PROPIOS')

	END

IF EXISTS  (
	SELECT * 
	FROM SYS.TABLES 
	WHERE NAME = 'VEHICULO_RENTING' AND SCHEMA_ID = SCHEMA_ID('dbo'))
	
	BEGIN 
		DROP TABLE dbo.VEHICULO_RENTING

		PRINT ('BORRADA LA TABLA VEHICULOS RENTING')

	END


IF EXISTS  (
	SELECT * 
	FROM SYS.TABLES 
	WHERE NAME = 'VEHICULO' AND SCHEMA_ID = SCHEMA_ID('dbo'))
	
	BEGIN 
		DROP TABLE dbo.VEHICULO

		PRINT ('BORRADA LA ABLA VEHICULOS')

	END

	CREATE TABLE VEHICULO (
		CODIGO SMALLINT IDENTITY(1,1),
		MATRICULA CHAR(8) NOT NULL,
		MARCA VARCHAR(15) NOT NULL, 
		MODELO VARCHAR(15) NOT NULL,

		CONSTRAINT PK_VEHICULO PRIMARY KEY (CODIGO)
	)

	CREATE TABLE VEHICULO_PROPIO (
		CODIGO_PROPIO SMALLINT IDENTITY(1,1),
		FECHA_COMPRA DATE NOT NULL,
		PRECIO FLOAT NOT NULL,


		CONSTRAINT FK_PROPIO_VEHILO FOREIGN KEY (CODIGO_PROPIO) REFERENCES VEHICULO (CODIGO)
	)

	CREATE TABLE VEHICULO_RENTING (
		CODIGO_RENTING SMALLINT IDENTITY(1,1),
		FECHA_INICIO DATE NOT NULL,
		PRECIO_MENSUAL FLOAT NOT NULL,
		MESES SMALLINT NOT NULL,

		CONSTRAINT FK_RENTING_VEHILO FOREIGN KEY (CODIGO_RENTING) REFERENCES VEHICULO (CODIGO)
	)

GO
SELECT * FROM SYS.TABLES


-- 19/01 Procedimientos________________________________________________________________________________________________________
IF OBJECT_ID('sp_CambioDomicilio', 'P') IS NOT NULL
	DROP PROCEDURE sp_CambioDomicilio;

GO -- DELIMITIER $$ EN mySQL
CREATE PROCEDURE sp_CambioDomicilio
	@NSS VARCHAR(15),
	@Rua VARCHAR(30),
	@Numero_Calle int,
	@Piso varchar(30),
	@CP char(5),
	@Localidade varchar(25)
AS
BEGIN
	UPDATE EMPREGADO
	SET RUA = @Rua,
		Numero_Calle = @Numero_Calle,
		Piso = @Piso,
		CP = @CP,
		Localidade = @Localidade
	WHERE NSS = @NSS;
END



IF OBJECT_ID('sp_DatosProxectos', 'P') IS NOT NULL
	DROP PROCEDURE sp_DatosProxectos;

GO
CREATE PROCEDURE sp_DatosProxectos
	@Num_Proxecto int, 
	@Nome_Proxecto varchar(25) OUTPUT,
	@Lugar varchar(25) OUTPUT,
	@Num_Departamento_Controla int OUTPUT
AS
BEGIN
	SELECT @Nome_Proxecto = NomeProxecto,
		@Lugar = Lugar,
		@Num_Departamento_Controla = NumDepartControla 
	FROM PROXECTO 
	WHERE NumProxecto = @Num_Proxecto;
END
GO
