USE BDEMPRESA25; 

GO
IF OBJECT_ID('DEPARTMENTOFUNCION', 'U') IS NOT NULL
	DROP TABLE DEPARTMENTOFUNCION


GO
CREATE TABLE DEPARTAMENTOFUNCION (
	NumDepartamento INT NOT NULL,
	Funcion VARCHAR(50),
	CONSTRAINT PK_FUNCION_DEPARTAMENTO PRIMARY KEY (NumDepartamento, Funcion),
	CONSTRAINT FK_DEPARTAMENTOFUNCION_DEPARTAMENTO FOREIGN KEY (NumDepartamento) REFERENCES DEPARTAMENTO (NumDepartamento)
)


GO
IF OBJECT_ID('PROXECTOFASE', 'U') IS NOT NULL
	DROP TABLE PROXECTOFASE

GO
CREATE TABLE PROXECTOFASE (
	NumProxecto INT NOT NULL,
	NomeFase VARCHAR(50) NOT NULL,
	Estado VARCHAR(30) NOT NULL,
	CONSTRAINT PK_PROXECTOFASE PRIMARY KEY (NumProxecto , NomeFase),
	CONSTRAINT FK_PROXECTOFASE_DEPARTAMENTO FOREIGN KEY (NumProxecto) REFERENCES PROXECTO (NumProxecto)
)
