USE EMPRESAHB26;

SELECT * FROM EMPREGADO
SELECT * FROM DEPARTAMENTO
SELECT * FROM FUNCION
SELECT * FROM TELEFONO
SELECT * FROM FAMILIAR

SELECT * FROM EMPREGADO_PROXECTO
SELECT * FROM HABILIDAD
SELECT * FROM HABILIDAD_EMPREGADO


select * from VEHICULO where nss = '0010010'



IF (OBJECT_ID('FUNCION', 'U') IS NOT NULL) 
	BEGIN
		PRINT('EXSISTE LA TABLA FUNCION')
		DROP TABLE FUNCION
	END

CREATE TABLE FUNCION (
	NumDepartamento int,
	Funcion VARCHAR(255),
	CONSTRAINT PK_FUNCION PRIMARY KEY (NumDepartamento, Funcion),
	CONSTRAINT FK_EMPREGADO_FUNCION FOREIGN KEY (NumDepartamento) REFERENCES DEPARTAMENTO (NumDepartamento)
)

INSERT INTO FUNCION (NumDepartamento, Funcion) VALUES (1, 'Ordenar escritorios')


IF (OBJECT_ID('HABILIDAD', 'U') IS NOT NULL) 
	BEGIN
		PRINT('HABILIDAD BORRADA')
		DROP TABLE HABILIDAD
	END


IF (OBJECT_ID('HABILIDAD_EMPREGADO', 'U') IS NOT NULL) 
	BEGIN
		PRINT('HABILIDAD_EMPREGADO BORRADA')
		DROP TABLE HABILIDAD_EMPREGADO
	END

CREATE TABLE HABILIDAD (
	codigo int IDENTITY(1,1),
	habilidad VARCHAR(255),
	CONSTRAINT PK_HABILIDAD PRIMARY KEY (codigo),
	CONSTRAINT UQ_habilidad UNIQUE (habilidad)
)

CREATE TABLE HABILIDAD_EMPREGADO (
	NSS VARCHAR(15),
	codigoHabilidad int,
	CONSTRAINT PK_HABILIDAD_EMPOREGADO PRIMARY KEY (NSS, codigoHabilidad) ,
	CONSTRAINT FK_HABILIDAD_EMPREGADO_HABILIDAD FOREIGN KEY (codigoHabilidad) REFERENCES HABILIDAD(codigo),
	CONSTRAINT FK_HABILIDAD_EMPREGADO_EMPREGADO FOREIGN KEY (NSS) REFERENCES EMPREGADO(NSS)
)

INSERT INTO HABILIDAD (habilidad) VALUES ('Desarollador rápido')
